//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanzauto.Infraestructure.SqlStatements {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatement() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finanzauto.Infraestructure.SqlStatements.SqlStatement", typeof(SqlStatement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [Courses]
        ///    (
        ///      [Name]
        ///     ,[CreatedBy]
        ///     ,[CreatedOn]
        ///    )
        ///VALUES
        ///    (
        ///      @Name
        ///     ,@CreatedBy
        ///     ,@CreatedOn
        ///	);.
        /// </summary>
        internal static string Course_Create {
            get {
                return ResourceManager.GetString("Course_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @Remove BIT = 1;
        ///
        ///UPDATE [Courses]
        ///SET  
        ///     [Remove] = @Remove
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Course_Delete {
            get {
                return ResourceManager.GetString("Course_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT [Id]
        ///      ,[Name]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[ModifiedBy]
        ///      ,[ModifiedOn]
        ///  FROM [Courses] 
        ///  WHERE ([Name] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;) 
        ///  AND [Remove] = @NotRemove
        ///  ORDER BY
        ///	[{0}] {1}
        ///    OFFSET 
        ///	    ((@Page - 1) * @RowsPage) ROWS
        ///    FETCH NEXT
        ///	    @RowsPage ROWS ONLY;.
        /// </summary>
        internal static string Course_GetCourses {
            get {
                return ResourceManager.GetString("Course_GetCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT 
        ///	COUNT(*)
        ///  FROM [Courses] 
        ///  WHERE ([Name] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;) 
        ///  AND [Remove] = @NotRemove;.
        /// </summary>
        internal static string Course_TotalRecords {
            get {
                return ResourceManager.GetString("Course_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [Courses]
        ///SET  
        ///     [Name] = @Name
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Course_Update {
            get {
                return ResourceManager.GetString("Course_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [Qualifications]
        ///    (
        ///      [Score]
        ///     ,[CourseId]
        ///     ,[StudentId]
        ///     ,[TeacherId]
        ///     ,[CreatedBy]
        ///     ,[CreatedOn]
        ///    )
        ///VALUES
        ///    (
        ///      @Score
        ///     ,@CourseId
        ///     ,@StudentId
        ///     ,@TeacherId
        ///     ,@CreatedBy
        ///     ,@CreatedOn
        ///	);.
        /// </summary>
        internal static string Qualification_Create {
            get {
                return ResourceManager.GetString("Qualification_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @Remove BIT = 1;
        ///
        ///UPDATE [Qualifications]
        ///SET  
        ///     [Remove] = @Remove
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Qualification_Delete {
            get {
                return ResourceManager.GetString("Qualification_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT Q.[Id]
        ///      ,Q.[Score]
        ///      ,C.[Name] AS [CourseName]
        ///	  ,CONCAT(T.[Name], &apos; &apos;, COALESCE(T.[LastName], &apos;&apos;)) AS [Teacher]
        ///	  ,CONCAT(S.[Name], &apos; &apos;, COALESCE(S.[LastName], &apos;&apos;)) AS [Student]
        ///      ,Q.[CourseId]
        ///      ,Q.[TeacherId]
        ///      ,Q.[StudentId]
        ///      ,Q.[CreatedBy]
        ///      ,Q.[CreatedOn]
        ///      ,Q.[ModifiedBy]
        ///      ,Q.[ModifiedOn]
        ///  FROM [Qualifications] Q
        ///  INNER JOIN Courses C ON Q.CourseId = C.Id  
        ///  INNER JOIN Teachers T ON Q.TeacherId = T.Id  
        ///  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Qualification_GetQualifications {
            get {
                return ResourceManager.GetString("Qualification_GetQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT 
        ///	COUNT(*)
        ///  FROM [Qualifications] Q
        ///  INNER JOIN Courses C ON Q.CourseId = C.Id  
        ///  INNER JOIN Teachers T ON Q.TeacherId = T.Id  
        ///  INNER JOIN Students S ON Q.StudentId = S.Id
        ///  WHERE (C.[Name] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  OR (CONCAT(T.[Name], &apos; &apos;, COALESCE(T.[LastName], &apos;&apos;)) LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  OR (CONCAT(S.[Name], &apos; &apos;, COALESCE(S.[LastName], &apos;&apos;)) LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search I [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Qualification_TotalRecords {
            get {
                return ResourceManager.GetString("Qualification_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [Qualifications]
        ///SET  
        ///     [Score] = @Score
        ///    ,[CourseId] = @CourseId
        ///    ,[TeacherId] = @TeacherId
        ///    ,[StudentId] = @StudentId
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Qualification_Update {
            get {
                return ResourceManager.GetString("Qualification_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U.Id, U.UserName, U.[Password], Rol.[Name] AS [Role]
        ///FROM Users U
        ///INNER JOIN Roles Rol ON U.RoleId = Rol.Id
        ///Where [UserName] = @UserName 
        ///And [Password] = @Password;.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [Students]
        ///    (
        ///      [Name]
        ///     ,[LastName]
        ///     ,[Identification]
        ///     ,[Email]
        ///     ,[PhoneNumber]
        ///     ,[CreatedBy]
        ///     ,[CreatedOn]
        ///    )
        ///VALUES
        ///    (
        ///      @Name
        ///     ,@LastName
        ///     ,@Identification
        ///     ,@Email
        ///     ,@PhoneNumber
        ///     ,@CreatedBy
        ///     ,@CreatedOn
        ///	);.
        /// </summary>
        internal static string Student_Create {
            get {
                return ResourceManager.GetString("Student_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @Remove BIT = 1;
        ///
        ///UPDATE [Students]
        ///SET  
        ///     [Remove] = @Remove
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Student_Delete {
            get {
                return ResourceManager.GetString("Student_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT [Id]
        ///      ,[Name]
        ///      ,[LastName]
        ///      ,[Identification]
        ///      ,[Email]
        ///      ,[PhoneNumber]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[ModifiedBy]
        ///      ,[ModifiedOn]
        ///  FROM [Students] 
        ///  WHERE ([Identification] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  AND [Remove] = @NotRemove
        ///  ORDER BY
        ///	[{0}] {1}
        ///    OFFSET 
        ///	    ((@Page - 1) * @RowsPage) ROWS
        ///    FETCH NEXT
        ///	    @RowsPage ROWS ONLY;.
        /// </summary>
        internal static string Student_GetStudents {
            get {
                return ResourceManager.GetString("Student_GetStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT 
        ///	COUNT(*)
        ///  FROM [Students] 
        ///  WHERE ([Identification] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  AND [Remove] = @NotRemove.
        /// </summary>
        internal static string Student_TotalRecords {
            get {
                return ResourceManager.GetString("Student_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [Students]
        ///SET  
        ///     [Name] = @Name
        ///    ,[LastName] = @LastName
        ///    ,[Identification] = @Identification
        ///    ,[Email] = @Email
        ///    ,[PhoneNumber] = @PhoneNumber
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Student_Update {
            get {
                return ResourceManager.GetString("Student_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [Teachers]
        ///    (
        ///      [Name]
        ///     ,[LastName]
        ///     ,[Email]
        ///     ,[PhoneNumber]
        ///     ,[CreatedBy]
        ///     ,[CreatedOn]
        ///    )
        ///VALUES
        ///    (
        ///      @Name
        ///     ,@LastName
        ///     ,@Email
        ///     ,@PhoneNumber
        ///     ,@CreatedBy
        ///     ,@CreatedOn
        ///	);.
        /// </summary>
        internal static string Teacher_Create {
            get {
                return ResourceManager.GetString("Teacher_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @Remove BIT = 1;
        ///
        ///UPDATE [Teachers]
        ///SET  
        ///     [Remove] = @Remove
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Teacher_Delete {
            get {
                return ResourceManager.GetString("Teacher_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT [Id]
        ///      ,[Name]
        ///      ,[LastName]
        ///      ,[Email]
        ///      ,[PhoneNumber]
        ///      ,[CreatedBy]
        ///      ,[CreatedOn]
        ///      ,[ModifiedBy]
        ///      ,[ModifiedOn]
        ///  FROM [Teachers] 
        ///  WHERE ([Name] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  OR ([LastName] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  OR ([Email] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  AND [Remove] = @NotRemove
        ///  ORDER BY
        ///	[{0}] {1}
        ///    OFFS [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Teacher_GetTeachers {
            get {
                return ResourceManager.GetString("Teacher_GetTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @NotRemove BIT = 0;
        ///
        ///SELECT 
        ///	COUNT(*)
        ///  FROM [Teachers] 
        ///  WHERE ([Name] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  AND ([LastName] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  AND ([Email] LIKE &apos;%&apos; + @Search + &apos;%&apos; OR @Search IS NULL OR @Search = &apos;&apos;)
        ///  AND [Remove] = @NotRemove;.
        /// </summary>
        internal static string Teacher_TotalRecords {
            get {
                return ResourceManager.GetString("Teacher_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [Teachers]
        ///SET  
        ///     [Name] = @Name
        ///    ,[LastName] = @LastName
        ///    ,[Email] = @Email
        ///    ,[PhoneNumber] = @PhoneNumber
        ///    ,[ModifiedBy] = @ModifiedBy
        ///    ,[ModifiedOn] = @ModifiedOn
        ///WHERE
        ///    [Id] = @Id;
        ///.
        /// </summary>
        internal static string Teacher_Update {
            get {
                return ResourceManager.GetString("Teacher_Update", resourceCulture);
            }
        }
    }
}
